### ISSUE TITLE
New TP 1.0.138 that builds all supported os

### ISSUE THREAD

**Issue by rgleason** [douwefokkema/AutoTrackRaymarine_pi#15]
Douwe, we have a new build that bdbcat and I have been working on, which does all the supported builds hopefully. Sometimes there are changes needed for android, but the template is much better.

Let me know when you would like to have it applied and to which branch (master or n2k)?  Thanks.

**Comment by douwefokkema** [comment]
Very good, best is to use the n2k branch. This is the version that is converted to use the new native NMEA2000 support in O. Not yet completely ready, I will test again on board coming weekend, using O master branch. So this will become the new version.

**Comment by rgleason** [comment]
Douwe,
You have changed to ShipDriver Template. 
I can's help you any longer.
Sorry.
Rick

**Comment by douwefokkema** [comment]
Rick, I thought that shipdriver was the general standard. So when I had problems compiling locally, I took the cmake.txt from radar_pi, which is the shipdriver one. But if there is a better standard that really is going to be the standard I would prefer to use that one. I even did not know that you were working on a standard. But my only practical concern is that the standard allows for a simple local compilation somehow. Please understand that I have spend big amounts of time on getting stuff to compile locally with the new wxWidgets 3.2 / 3.3. So now I have reverted to the commit where you have merged your earlier work and put my changes to the sources (scr and include) on top of that. This you will find in the branch new.

**Comment by rgleason** [comment]
Douwe,  the two templates (from Testplugin_pi or from Shipdriver_pi)  are actually "systems" which have various directories and files. The purpose of course is to simplify the complexity of building all these different OS versions (using circleci.com), and deploy to a good repository (cloudsmith) which can be accessed by the Plugin Manager to download the tarballs for various plugins.  These templates both create one metadata file for every OS version of the plugin.

Testplugin Template

The Testplugin Template was the first "system" and it's advantage is that the settings a developer needs to change are generally in the CMakeLists.txt.  We just updated Testplugin so that we are building all the supported versions and the naming of files in the config.yml and ci/ directories is consistent and comprehensible. Also I have made comments in the .circleci/config.yml separating the Opencpn 5.6.1 and 5.8.2 builds and explaining pertinent aspects of each build. 

I totally understand the need to build locally, so does Jon who uses Linux. Using Windows, I usually build, every plugin update locally and then test it in the current version of Opencpn, using the import plugin and picking the tarball from the "build" directory.  I generally use a bash prompt with the plugin's git clone directory as the location.  I've forgotten if you use windows or not. This is for windows.

Before executing the bash prompt "bash  ./bld.bat" from your plugins clone directory.  You will want to first modify the bld.bat file to point the "set" commands to the correct location for your wxWidgets!  I generally put all my cloned plugin directories and several versions of wxWidgets under "C:\Users\fcgle\source\ "  simply because it seemed like the proper place for this.

Then make sure that the "build" directory is totally clean with nothing in it. Then at the bash prompt issue "bash  ./bld.bat"  which executes a batch file with the necessary commands.  (this is for windows)  

After executing Then I have to check the bash prompt immediate output to correct any deficiencies and some files land in the "build" directory. From there the output is piped to "output.txt" located in the "build" directory. If the necessary tarballs do not get added to the "build" directory, I then search the "output.txt" for "errors" and correct them.

I can help you get setup to build your plugins yourself if you would like. However I can build them for you until decide to. (We discussed this earlier.)  Once you get setup it is not difficult, but you need to sign up for appveyor, circleci and cloudsmith accounts and then there are some setup steps and authorization keys needed.  This part is necessary no matter which system you decide to use.

Shipdriver

Leamas and Mike would say that their Shipdriver template is more automatic because it populates the master catalog automatically if you set it up correctly, and they would probably say that it is the "standard" because Leamas designed and built it more recently.  (I personally like the control that Testplugin's system for getting created metadata from the cloudsmith repository, commited  into the opencpn/plugins master branch, the same as the "Plugin Manager" "master catalog",  because it is more flexible, in my opinion.)  However both ways work fine.

I use both system, but know Testplugin better. Shipdriver does have some nice features. They are both somewhat complicated underneath and  it is a bit of a project to switch between systems. You can't just copy the cmakelists.txt file. However it can be done.  We converted vdr_pi and logbookkonni_pi to the shipdriver template and I am trying to maintain and update those.   

I hope that background helps.

**Comment by rgleason** [comment]
` This you will find in the branch new.`

Ok, thanks. I will clone that and update it and then push it back to your repos.  What OS are you using to build locally?

PS I sympathize with and thank you for the time spent!

**Comment by douwefokkema** [comment]
Rick, thanks for the explanations, this clarifies things for me. 
Locally I develop on Windows 10 and 11, using Visual Studio (main reason to use Windows, I like the real VS better than Code). Then I use Window Subsystem for Linux (WSL) to compile for Linux. As a development environment this suits my needs. However testing O on WSL does not work, graphical issues. Regarding spending my time, I prefer to concentrate on functionality of the plugins (radar and autotrack) instead of diverting to scripts en cmake stuff.

**Comment by rgleason** [comment]
I totally understand.  Yes, you should be able to use VS to build for windows, I've done that too, but as a separate plugin, then copy the dll and pdb files to %localappdata%/opencpn/plugins/
or  similar C:\Users\fcgle\AppData\Local\opencpn\plugins  the rebuild windows and test.
(You should copy from the relwithdebinfo folder to debug the plugin, but you know that.)
