### ISSUE TITLE
Microsoft Windows Fails   version 1.18.1

### ISSUE THREAD

**Issue by rgleason** [douwefokkema/AutoTrackRaymarine_pi#22]
After updates to TP Frontend2, commit and push to my remote repository  branch "new"
https://github.com/rgleason/AutoTrackRaymarine_pi/tree/new
If I can't build for Windows, I can't even begin to test it.
On the good side 16 OS were built, and MacOs, Windows and Android did not build.

The builds have deployed to the CS Opencpn AutoTrackRaymarine-Beta  Repository.

Here is the error report for Windows.  Can you fix it?  Does it have something to do with texFont.cpp?
https://ci.appveyor.com/project/rgleason/autotrackraymarine-pi/builds/47737254
```
  TexFont.cpp
     Creating library C:/project/ocpn_project/build/Release/AutoTrackRaymarine_pi.lib and object C:/project/ocpn_project/build/Release/AutoTrackRaymarine_pi.exp
AutoTrackRaymarine_pi.obj : error LNK2019: unresolved external symbol "public: __thiscall opencpn_plugin_118::opencpn_plugin_118(void *)" (??0opencpn_plugin_118@@QAE@PAX@Z) referenced in function "public: __thiscall AutoTrackRaymarine_pi::AutoTrackRaymarine_pi(void *)" (??0AutoTrackRaymarine_pi@@QAE@PAX@Z) [C:\project\ocpn_project\build\AutoTrackRaymarine_pi.vcxproj]
AutoTrackRaymarine_pi.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall opencpn_plugin_118::RenderGLOverlayMultiCanvas(class wxGLContext *,class PlugIn_ViewPort *,int,int)" (?RenderGLOverlayMultiCanvas@opencpn_plugin_118@@UAE_NPAVwxGLContext@@PAVPlugIn_ViewPort@@HH@Z) [C:\project\ocpn_project\build\AutoTrackRaymarine_pi.vcxproj]
PreferencesDialog.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall opencpn_plugin_118::RenderGLOverlayMultiCanvas(class wxGLContext *,class PlugIn_ViewPort *,int,int)" (?RenderGLOverlayMultiCanvas@opencpn_plugin_118@@UAE_NPA
```

The second version of Windows has similar errors
https://app.circleci.com/pipelines/github/rgleason/AutoTrackRaymarine_pi/66/workflows/8802c0da-bb84-468e-97b7-2ef9db16b9bc/jobs/809
TexFont.cpp
     Creating library C:/Users/circleci.PACKER-64B08804/project/build/RelWithDebInfo/AutoTrackRaymarine_pi.lib and object C:/Users/circleci.PACKER-64B08804/project/build/RelWithDebInfo/AutoTrackRaymarine_pi.exp
AutoTrackRaymarine_pi.obj : error LNK2019: unresolved external symbol "public: __thiscall opencpn_plugin_118::opencpn_plugin_118(void *)" (??0opencpn_plugin_118@@QAE@PAX@Z) referenced in function "public: __thiscall AutoTrackRaymarine_pi::AutoTrackRaymarine_pi(void *)" (??0AutoTrackRaymarine_pi@@QAE@PAX@Z) [C:\Users\circleci.PACKER-64B08804\project\build\AutoTrackRaymarine_pi.vcxproj]
AutoTrackRaymarine_pi.ob

Can you fix this?

I am going to push the ones that built up to the master Catalog.

**Comment by rgleason** [comment]
What I have determined:
Original files existing
- AutoTrackRaymarine_pi\src\TexFont.cpp
- AutoTrackRaymarine_pi\src\TexFont.h

TestPlugin files that are required.
- AutoTrackRaymarine_pi\ocpnsrc\TexFont.cpp
- AutoTrackRaymarine_pi\ocpninclude\TexFont.h

I have compare the two texFont.cpp and they are different in some significant ways.
There are if dif for android etc.

I am going to try excluding the original files by renaming them.

**Comment by rgleason** [comment]
Both Windows builds and both Android builds are failing still.

After trying to build windows locally, I found TexFont errors still and had to include Jon's ocpnsrc/TexFont.cpp  and ocpninclude/Texfont.h  and move the original src/Texfont.cpp and src/TexFont.h into a new folder src/OLD-texfont so it would be not be found during building.

I think this should fix the Windows problem but there are still [errors due to some undefined external symbol.](https://app.circleci.com/pipelines/github/rgleason/AutoTrackRaymarine_pi/67/workflows/8c83abe3-c668-4520-8629-39726b738437/jobs/852)
I think this has to do with the use of API 118 for this plugin.

Jon has the current TestPlugin set up to just use API116!!!
We have to get the right files for API118!!

Also we should clean this up so that it is good for other plugins.
Do we have to have an API116 directory and a API118 directory or can we just use the most current API???

**Comment by rgleason** [comment]
@bdbcat  Can you give me some guidence here with regard to use of API files?
Which ones are needed and where do I get them?
Also, shouldn't we update TestPlugin_pi  Template so that it is set for all plugins using API118???

**Comment by rgleason** [comment]
**Problem:  Need for API 118 and Testplugin only has API 116!!!!** 

1. src/ODAPI.h is required by PluginSetup.cmake  
2. I had un-commented this out in CMakeLists.txt
3. This is file is used by Ocpn_draw to communicate with other plugins to handle Boundaries created in ODraw or to send an alarm to Watchdog, etc..
4. AutoTrackRaymarine does not have these features.
5. So I am commenting it out again.
6. I think the problem is related to API 118 files. So I have taken files from the most recent OpenCPN build

- Copied from OpenCPN\build\RelWithDebInfo\opencpn.lib
- to  source\AutoTrackRaymarine_pi\libs\ocpn-api\msvc\opencpn.lib
- Copied from source\repos\OpenCPN\include\ocpn_plugin.h
- to  source\AutoTrackRaymarine_pi\libs\ocpn-api\ocpn_plugin.h

Now when I try building locally with the bash prompt
`bash ./bld.bat`

An exe and tar.gz file is created under the "build" directory.
Note that I first had to run the Developer Command Prompt VS2022 to be able to see the text piped to "build/output.txt" so that I  could identify the errors in the setup. Once I thought those were fixed I tried the bash prompt which does not recognize the pipe command for output to "output.txt" file.

**Comment by rgleason** [comment]
So this is building now because I updated the files to API 118.
I think I should just do the same for testplugin_pi ?????

**Comment by rgleason** [comment]
Version 1.18.4.0 has been pushed up to the "new" branch and is building now.
https://github.com/rgleason/AutoTrackRaymarine_pi/tree/new

**Comment by rgleason** [comment]
The problem now with AutoTrackRaymarine 1.18.4.0 now is that it is failing when installed.
It does not initiate properly in Windows and the Autopilot window does not appear, and preferences is not working either.
After trying to use the plugin it corrupts the entire plugin list so that all the plugins have a green puzzle icon.

To get back to normal, I have to close opencpn, open opencpn, pick safe boot becausee there was a bad plugin.
Then install the simpler version of AutoTrackRaymarine  and then Close Opencpn and reopen, and then enable the old version of AutotrackRaymarine and all the right icons come back.  See attached which is the expected nav screen for this plugin which does not appear and the expected preferences.

![Screenshot (1613)](https://github.com/douwefokkema/AutoTrackRaymarine_pi/assets/2363959/b49ffb4b-1a00-434c-93e1-16da3e0f0561)


 
![Screenshot (1614)](https://github.com/douwefokkema/AutoTrackRaymarine_pi/assets/2363959/2f5e95c1-1ecb-4856-a9e5-1a021105eac4)

**Comment by rgleason** [comment]
I am going to try to debug this in VS2022 now.

VS2022 How to clean, build, and debug Plugins.
=====================
1. Build locally as we normally do as a standalone plugin. Done
2. Then copy the ocpn_draw_pi.dll and ocpn_draw_pi.pdb  files to 
%localappdata%\opencpn\plugins    Done
or
C:\Users\fcgle\AppData\Local\opencpn\plugins   Done, same.
3. Then start VS2022 run clean, and then build. Done
4. Then start debugging.    Done
5. Add breakpoints to see how it runs.

**Comment by rgleason** [comment]
Well, it used to work, but now OpenCPN immediately removes any misbehaving plugin, so I cannot debug!!
Even when I try to "Import Plugin"  what happens is AutoTrackRaymarine is instantly removed in a flash.

Later: Then I messed around more withing VS2022 and was able to select and load the old version that just works with windows. Then I tried to "Import Plugin" while still in VS2022 and it imported, but I am unable to install it. It is removed instantly.

We need to have some switch to turn this OFF or we won't be able to debug plugins.  I think I wrote about this earlier.
As it stands now it is impossible to debug this plugin any further using VS2022 with Windows.

Using the Import Plugin feature is not the right way to test plugins, but I thought I would try  it to see what happens and sure enough the dll is removed every time!

![1 Successful-Import](https://github.com/douwefokkema/AutoTrackRaymarine_pi/assets/2363959/7c61b2d6-8923-4fd5-abe6-b0887a8dd40b)
![2 Choices](https://github.com/douwefokkema/AutoTrackRaymarine_pi/assets/2363959/e04013a5-678b-46f4-b325-ee07062d13d7)
![3 Select-Download-Error](https://github.com/douwefokkema/AutoTrackRaymarine_pi/assets/2363959/6ad341d4-5099-4fc1-b3ce-0103b3760c19)
![4Older-installs-works](https://github.com/douwefokkema/AutoTrackRaymarine_pi/assets/2363959/d6244683-60b3-4720-9460-5ecb8894f4b1)

**Comment by rgleason** [comment]
@bdbcat is there any solution to getting this to debug?

**Comment by rgleason** [comment]
Douwe just wrote:

Rick,

Here with me the branch "new" does compile locally under Windows, after my last change to the CmakeLists.txt:

```
project(${PACKAGE})
+add_subdirectory("opencpn-libs/api-18")
+ set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
```

Did you include this change?    Cheers, Douwe

I guess I did it another way.  Is Douwe building in VS2022 with this code?  Looks like....

Well, I just realized that this code is fine for a final build perhaps, but there is no way to build the plugin locally with this code, and since we are trying to solve problems first, I think I need to include the files hard coded.

The above would work if you are not building the plugin as a standalone, but with Opencpn and the opencpn-lib directory.

**Comment by rgleason** [comment]
There is something wrong with initialization or an Icon, or I am missing some code, because it does not load properly.
I cannot push this up to plugins master as it will screw other plugins up and mess up users.

**Comment by rgleason** [comment]
I have pushed these builds to PIM Beta for further testing and fixing. Fails in Windows.
[AutoTrackRaymarine 1.18.4.0 fails in Win](https://github.com/OpenCPN/plugins/pull/954/commits/e89658f02ee979f3af0c2e02331d52b35267a157)

**Comment by rgleason** [comment]
Well, perhaps it is something else causing the problem, because PIM seems to find the plugin acceptable.

See portions of the opencpn.log
[autotrackraymarine-opencpn-log.txt](https://github.com/douwefokkema/AutoTrackRaymarine_pi/files/12294851/autotrackraymarine-opencpn-log.txt)

**Comment by rgleason** [comment]
I have pushed the successful builds to the Beta Catalog and bdbcat has merged it.
This needs to be tested and fixed now.

**Comment by bdbcat** [comment]
Rick...
I appreciate your good intentions.
But willy-nilly grabbing source files from who-knows-where to get a successful build is the wrong way to proceed.
If you will proceed step-by-step, asking for help, I can help.  But at this point, I have no idea what works, what hacks have been done.  Or even if the OP (Douwe?) is involved.  So I can find no way to usefully contribute.
Going back to the very first report of failure to build:
```

     Creating library C:/project/ocpn_project/build/Release/AutoTrackRaymarine_pi.lib and object C:/project/ocpn_project/build/Release/AutoTrackRaymarine_pi.exp
AutoTrackRaymarine_pi.obj : error LNK2019: unresolved external symbol "public: __thiscall opencpn_plugin_118::opencpn_plugin_118(void *)" (??0opencpn_plugin_118@@QAE@PAX@Z) referenced in function "public: __thiscall AutoTrackRaymarine_pi::AutoTrackRaymarine_pi(void *)" (??0AutoTrackRaymarine_pi@@QAE@PAX@Z) [C:\project\ocpn_project\build\AutoTrackRaymarine_pi.vcxproj]
AutoTrackRaymarine_pi.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall opencpn_plugin_118::RenderGLOverlayMultiCanvas(class wxGLContext *,class PlugIn_ViewPort *,int,int)" (?RenderGLOverlayMultiCanvas@opencpn_plugin_118@@UAE_NPAVwxGLContext@@PAVPlugIn_ViewPort@@HH@Z) [C:\project\ocpn_project\build\AutoTrackRaymarine_pi.vcxproj]
PreferencesDialog.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall opencpn_plugin_118::RenderGLOverlayMultiCanvas(class wxGLContext *,class PlugIn_ViewPort *,int,int)" (?RenderGLOverlayMultiCanvas@opencpn_plugin_118@@UAE_NPA

```

This is indicative of incorrect plugin API.  Has nothing to do with TexFont.
Can we return to that point, and proceed stepwise?

**Comment by rgleason** [comment]
Dave
> This is indicative of incorrect plugin API. Has nothing to do with TexFont.
> Can we return to that point, and proceed stepwise?

Yes, I hope I have learned that now. 

Dave, there have not been many changes. just some changes to CMakeLists.txt to provide paths to missing files (as shown in the compile errors.) and then getting the right files for API 118 as described above. The version of OpenCPN was my local updated version from opencpn/master

    Copied from OpenCPN\build\RelWithDebInfo\opencpn.lib
    to source\AutoTrackRaymarine_pi\libs\ocpn-api\msvc\opencpn.lib
    Copied from source\repos\OpenCPN\include\ocpn_plugin.h
    to source\AutoTrackRaymarine_pi\libs\ocpn-api\ocpn_plugin.h

That fixed it. Because the plugin builds locally and seems to work (menus etc) but it has to be tested for communications.
Then I saw that Douwe had made a commit to be able to build, so I merged that commit remotely. It failed to build, so I just reverted the commit, and the plugin built Ok again.   This has been push up to the Beta Catalog now as what we need now is testing.

The two [android builds failed because of some glob problem](https://app.circleci.com/pipelines/github/rgleason/AutoTrackRaymarine_pi/71/workflows/4fc34e24-f0f4-4ce4-a3ba-6aeb80edf10c/jobs/919)

I should probably close this extemporaneous log now.

**Comment by rgleason** [comment]
Brain bleep here. That's right it is compiling, but not working.   
Ok I will revert back to where this happened

**Comment by rgleason** [comment]
Dave, 
I propose to revert back to  [1.18.1.0 + TP1.0.253.0](https://github.com/rgleason/AutoTrackRaymarine_pi/commit/ae8d0c1f3bdaa65e611060ca799887f83b14b03d)

https://github.com/rgleason/AutoTrackRaymarine_pi/commits/new

Just after Douwe's changes and including updates to TP 1.0.253

Does that look right to you?

**Comment by rgleason** [comment]
Well that was easy.  I reverted to just before that and had to reapply TP1.0.253.
Then built it locally with no changes, and it works.
No need to monkey with API files. Douwe had the right ones all along.
Will push to PIM master
