### ISSUE TITLE
Streamline + Libs

### ISSUE THREAD

**Issue by rgleason** [douwefokkema/AutoTrackRaymarine_pi#28]
@douwefokkema  @bdbcat

https://github.com/rgleason/AutoTrackRaymarine_pi/tree/streamline
deployed to https://cloudsmith.io/~opencpn/repos/autotrackraymarine-beta/packages/?q=1.18.21
Actually, I did merge "new" into "master" in my remote repository, So the checkout of streamline is updating the tip.

I think we have too many libs, or at least it looks like it to me, for this plugin.
However the plugin appears to be working although I can't test it.

The autotrackraymarine_pi/libs directory has
```
GL     <--not in build/libs    <-needed for sure  we do reference these in cmakelists.txt.
glu    <--in build/libs       <-needed for sure
jsoncpp    <--in build/libs   <-- we removed json files from src, so this must be needed.
nmea0183   <--in build/libs   <-needed for sure
ocpn-api    <--in build/libs   <-needed for sure
pluginDC   <--in build/libs     <-needed for sure
serial    <--in build/libs
tinyxml   <--in build/libs       <--needed for flatpak
wxJSON   <--not in build/libs   <--these are referenced in cmakelists.txt
```

The autotrackraymarine_pi/build/libs directory has
```
glu
jsoncpp
nmea0183
ocpn-api
pluginDC
serial
tinyxml
```

Can any of the libs  be removed because they are not used?
Also same question for includes in CMakeLists.txt
Does "serial" permit  nmea0183 serial connections too?   -No, I believe this version outputs nmena0183 or serial so a device can be attached that converts nmea0183 to n2k to direct the  Raymarine EVO1 via n2k.

**Comment by rgleason** [comment]
Actually, I did merge "new" into "master" in my remote repository, So the checkout of streamline is updating the tip.
So the streamline branch is ok.

Below is Wrong.

> I just realized that I just updated from the "master" branch using git checkout -b streamline.
> So I have updated the older version using the streamline branch.

**Comment by douwefokkema** [comment]
Sorry, I do not understand why you are using older branches. The released version is found in the master branch. Yes, it is possible that there are unused libraries, these were needed in the original version where the NGT-1 was directly controlled by the plugin. the master version is much nicer and less complex.

**Comment by rgleason** [comment]
Douwe, my mistake.  Everything is ok. I had remembered that we were using "new" branch and forgot that we merged that with "master".

I did use "master" branch to create the "streamline" branch, so the changes made so far are OK and are in github.com/rgleason/autotrackraymarine/streamline   (as above)  and those changes are good. There are more coming.

Sorry about the confusion.

If you'd like to prepare your repository you could go to your local git folder 
git branch -va    make sure you are on 'master"
git status      make sure about changes and commits, etc.
git checkout -b streamline   create a new local branch named streamline and change to that.
Then push that branch up to your remote github repository.

Then I will be able to make a PR to that branch on your remote repository.
Otherwise I can merge to my master branch and make a PR to your master.
Its your call.

(We won't be doing this just yet)

**Comment by douwefokkema** [comment]
Rick, sorry about the delay, was out with the boat again. But yes, the "streamline" branch is there now. I am really interested in your changes.

**Comment by rgleason** [comment]
Douwe I made a PR from rgleason/streamline to douwef/streamline using the Pull Request tab in github online.
it looks like this when you are setting up the Compare:  
  
douwef/streamline <----- rgleason/streamline  (watch the arrow!!)

Then you select to make a merge. It tests to see if there are conflicts. (I have already done this, but you could too) 

Now, since there are no conflicts you can decide to merge.

We will have some more improvements later using opencpn-libs submodule.

**Comment by douwefokkema** [comment]
Rick, I merged your PR, no problems. And the outcome builds as it should. Additionally, I removed a few unused lines in PreferencesDialog.h. I pushed this update to streamline branch. I did no functional tests yet, have to be on the boat for that, planned to go later this week, but weather is getting worse, will see.

**Comment by rgleason** [comment]
Thanks Douwe. Hope it works as expected.
