### ISSUE TITLE
Bug: sublibs branch: indirect_directories used

### ISSUE THREAD

**Issue by rgleason** [douwefokkema/AutoTrackRaymarine_pi#30]
```
include_directories(BEFORE ${PROJECT_SOURCE_DIR}/opencpn-libs/glu/include)   <---Problem
include_directories(BEFORE ${PROJECT_SOURCE_DIR}/libs/serial)   <---private lib
```

**Comment by douwefokkema** [comment]
These 2 lines remained there from the time that this plugin controlled the Actisense controller direct. Lines removed in streamline branch, still compiles without problem Streamline branch was tested on-board (before this update). Streamline branch merged into master and pushed.
