### ISSUE TITLE
Douwe, we need a new "sublibs" branch added to your repo

### ISSUE THREAD

**Issue by rgleason** [douwefokkema/AutoTrackRaymarine_pi#31]
In your online github, here from the "master" branch  

https://github.com/douwefokkema/AutoTrackRaymarine_pi

Just click on "master" button and then type in the field "sublibs" to checkout a new branch.

Then I will make a PR from my sublibs to your sublibs.  

We have continued working since "streamline" branch was created, using the opencpn-libs submodule.
For more information about the submodule what the rules are and how you use it, please see
https://github.com/jongough/testplugin_pi/issues/332

**Comment by douwefokkema** [comment]
Done

**Comment by rgleason** [comment]
OK, Thanks. Now there is a PR for you to merge. Thanks.
