### ISSUE TITLE
CMakeSettings.json    -what is it for?

### ISSUE THREAD

**Issue by rgleason** [douwefokkema/AutoTrackRaymarine_pi#33]
Douwe in your root dir of the plugin,  sublibs branch. What is this file for?  Does it do anything?
I would like to remove it if it is leftover from some previous configuration.
https://github.com/douwefokkema/AutoTrackRaymarine_pi/blob/88e31a62d58976bf79476c0c8f801846aa432a45/CMakeSettings.json

**Comment by douwefokkema** [comment]
This file seems to be part of the history. I removed it. I also updated opencpn-libs, compiles fine locally now.

**Comment by rgleason** [comment]
Thanks.
