### ISSUE TITLE
20 builds problem

### ISSUE THREAD

**Issue by rgleason** [douwefokkema/AutoTrackRaymarine_pi#34]
Douwe, yes you mention having 20 builds.
Now I realize that since the plugin is using API 118, you don't need 20 builds, because some of them just won't be accepted in PIM and they won't work anyway.

For example

- msvc (wx312) for OpenCPN 5.6   that requires wxWidgets 312 and will only go up to Api 17.

However 
-msvc (wx322) for OpenCPN 5.8 will work with Api 118.

So basically, I think we need to eliminate all the OpenCPN 5.6 builds. Isn't this correct?

The easiest way to do this is to edit the circleci/config.yml file.
You put a "#"  sign in front of every line below the Opencpn 5.6 Title.

- LATER: No it's not that.  I have to figure this out. I think you comment out the upper part only.
- Will come back.

**Comment by rgleason** [comment]
I think this will do what is necessary   in the circleci/config.yml file

```
## -------------------------------------------
## OpenCPN 5.6.2 Plugins  Frozen - 28/05/2023
## ------------------------------------------
#        - build-macos:
#             <<: *std-filters
## Appveyor no longer builds for Windows.
#        - build-msvc-2022:
#            <<: *std-filters
#        - build-debian-armhf-10-buster:
#            <<: *std-filters
#        - build-debian-armhf-10-buster-gtk3:
#            <<: *std-filters
#        - build-debian-arm64-10-buster:
#            <<: *std-filters
#        - build-debian-x86_64-10-buster:
#            <<: *std-filters

## -------------------------------------
## UBUNTU OS  Frozen - 28/05/2023  DROP
## -------------------------------------
## KEEP needed for Raspbian OpenCPN v5.6
#        - build-ubuntu-armhf-1804-buster:
#            <<: *std-filters
##        - build-ubuntu-x86_64-1804-bionic:
##            <<: *std-filters
```

**Comment by rgleason** [comment]
See https://github.com/jongough/testplugin_pi/issues/341

**Comment by rgleason** [comment]
Made a PR to you https://github.com/douwefokkema/AutoTrackRaymarine_pi/pulls

**Comment by douwefokkema** [comment]
Done, I pulled it and after pushed the changes that I did earlier today according to your recommendations. I am however completely lost on what I am doing here and even on what we want to achieve with this infinite series of updates.

**Comment by rgleason** [comment]
Douwe, we learn and realize things.  We were building Opencpn 5.6 metadata and tarballs which don't work with api118 and they aren't even loaded into PIM, but why even spend the time to build and deploy plugin versions that don't work?

That is why we commented out the O5.6 builds in the circleci/config.yml which tells circleci cloudservice what to build.

Sorry there is just one more change in a couple of days. Dave and Alec are updating the common submodule opencpn-libs.

Then if everything is working you can push to your master.

**Comment by rgleason** [comment]
Closing now. Thanks for the work.
