### ISSUE TITLE
maybe an issue?

### ISSUE THREAD

**Issue by dwynalda** [douwefokkema/AutoTrackRaymarine_pi#36]
I've had a few days to experiment with the plug-in controlling an evolution autopilot via ngt1 and I can make it go from standby to auto and back or use the buttons in the plug-in to switch the autopilot direction.  

I've tried double clicking auto to follow a route with limited success (probably my lack  of opencpn knowledge).  

I am left with two questions at this point:
1.  when I click things in the autopilot or the plug-in the actions are made on the evolution p70.  but the plug-in never shows the change from standby to auto or back that shows on the actual device. is this normal?   is it possible it is only writing to the device but not reading?  I have installed the device ad a connection in opencpn but not in openplotter serial app.  I tried configuring it in the serial app but it didn't function. I tried adding it to canbus in serial and that didn't help either.  
I'm hoping you can suggest something I might have done wrong.  remove and reinstall of plug-in and connection in opencpn doesn't seem to solve it. the not will show lots of incoming packets if I install it in signalk so I am sure it functions. but no status shown in opencpn

2nd question is related.  is it possible to use ngt1 to xfer data to plug-in *and* signalk or are two ngt1's required?  would you recommend doing that or use some other device to get nmea2000 info into signalk?

I'm sure I've done something incorrectly with the install but apparently I have done it consistently as the result seems to stay the same.

**Comment by douwefokkema** [comment]
As I have no experience with OpenPlotter and SignalK I have to guess. So I have not been able to test on this environment. But your conclusion that transmitting messages from the plugin to the autopilot works seems right. And the other way does not work. Could it be that another device (SignalK or the serial app?) is reading the messages from the serial port of the NGT-1? In that case OpenCPN would not see the messages and might still be able to transmit. May be you could try to disable all other apps except OpenCPN with the AutotrackRaymarine plugin. And as you did, the port number of the NGT-1 should be selected in the OpenCPN connectons, serial NMEA2000. If we have to go deeper into this, better mail me with a PM and we switch to normal mail.

**Comment by dwynalda** [comment]
I suspect your feeling is correct.  I may do a fresh install on raspbian
and see if I can make opencpn work without the other stuff configured at
all... Then step by step configure the others until it - hopefully - all
works.

I suspect the linking of the USB device to a specially named device (that
open plotter serial does) is the culprit.     I'll contact you with my
personal stuff if I need your help for future diagnosis.

**Comment by douwefokkema** [comment]
The cause of the issue was that the method SetLabel() on a wxTextCtrl works fine under Windows but does not work on Linux. I replaced this SetLabel() with SetValue() which works fine under both systems. Solution is in master branch. I will see if Rick can generate a new version for the beta repository.

**Comment by rgleason** [comment]
https://github.com/rgleason/AutoTrackRaymarine_pi
Douwe fixed, pushed to opencpn/plugins master
https://github.com/OpenCPN/plugins/pulls
bdbcat will merge.

**Comment by rgleason** [comment]
I believe this can be closed now by the original poster @dwynalda

**Comment by dwynalda** [comment]
Yes.  All set. Ty.

**Comment by rgleason** [comment]
Ty thanks for responding, but you have to physically "Close" this issue down at the bottom. The original poster has to do it. Thanks.

**Comment by dwynalda** [comment]
thank you!  glad to test!

**Comment by dwynalda** [comment]
done.  sorry this process is new to me.  I had to be on PC or I couldn't
see the button ;-)

Douwe had me test a windows version of .33 earlier this week with a
preference to discount the value of xte and use the straight angle to the
next waypoint (despite being on/off course).   it works great but I'd
really like to use it on PI so I don't have to use windows PC, keep the
generator running to keep PC up.   My PI is integrated under the deck and I
control via VNC so it's definitely preferred -- but as of this moment it
doesn't show the new version.   is this something that happens when you
push it out?   .32 still shows in the plugin when updating.

**Comment by rgleason** [comment]
When it reaches the Plugin Manager catalog (PIM) we generally are trying to provide plugins for all supported OS except for some specific plugins.  Since Douwe had you testing, it may not have been available for more than several OS at the time.  I think David will be updating PIM master catalog with the new version of autotrackraymarine fairly soon.
