### ISSUE TITLE
...effect on AutoTrackRaymarine is unknown without further investigation.

### ISSUE THREAD

**Issue by rgleason** [douwefokkema/AutoTrackRaymarine_pi#42]
See 
GetN2000Payload(nmea2kId, ev) returning wrong size of vector   #3488
https://github.com/OpenCPN/OpenCPN/issues/3488#issuecomment-1881440505

> However, there are at least two plugins (javascript and AutoTrackRaymarine) that do not use the n2K library. These two plugins parse the N2K payload manually, picking out the required fields by simply knowing their offsets and format within the payload vector.
> As you have described, javascript plugin knows how to detect and discard the extraneous byte. But the effect on AutoTrackRaymarine is unknown without further investigation.

**Comment by bdbcat** [comment]
There is nothing to do here.
The current code in O584, and O59, will not be changed.
Please close, to avoid red herring
