### ISSUE TITLE
Some Log errors

### ISSUE THREAD

**Issue by rgleason** [douwefokkema/AutoTrackRaymarine_pi#9]
```
21:37:31.764    INFO pluginmanager.cpp:2540 PlugInManager:  C:\Users\fcgle\AppData\Local\opencpn\plugins\AutoTrackRaymarine_pi.dll
21:37:31.764    INFO pluginmanager.cpp:2541         Plugin common name: AutoTrackRaymarine
21:37:31.764    INFO pluginmanager.cpp:2543         API Version detected: 117
21:37:31.764    INFO pluginmanager.cpp:2544         PlugIn Version detected: 1.1.1
21:37:31.780 MESSAGE SerialPort.cpp:67 AutoTrackRaymarine_pi: pcCommPort2=\\.\
21:37:31.780 MESSAGE SerialPort.cpp:155 AutoTrackRaymarine_pi Error com port
21:37:31.780 MESSAGE SerialPort.cpp:87 AutoTrackRaymarine_pi Error making serial port for NGT-1
21:37:31.780 MESSAGE SerialPort.cpp:96 AutoTrackRaymarine_pi: error getting timeouts
21:37:31.780 MESSAGE SerialPort.cpp:105 AutoTrackRaymarine_pi error setting timeouts
21:37:31.780 MESSAGE SerialPort.cpp:108 AutoTrackRaymarine_pi Device is a serial port, send the startup sequence.
21:37:31.905 MESSAGE NGT1Read.cpp:59 AutoTrackRaymarine_pi: NGT1Input thread created, prio= 50
21:37:31.968 MESSAGE NGT1Read.cpp:66 AutoTrackRaymarine_pi: NGTInput1 thread starting
21:37:31.968 MESSAGE NGT1Read.cpp:95 AutoTrackRaymarine_pi: Unable to read from NGT1 device
21:37:31.968 MESSAGE NGT1Read.cpp:76 AutoTrackRaymarine_pi: NGT1Read thread stopping
21:37:31.968 MESSAGE pluginmanager.cpp:1168 Checking plugin candidate: C:\Users\fcgle\AppData\Local\opencpn\plugins\calculator_pi.dll



21:37:32.031 MESSAGE OCPNPlatform.cpp:1101 ERROR Loading translation catalog for:  opencpn-AutoTrackRaymarine_pi
21:37:32.046 MESSAGE OCPNPlatform.cpp:1101 ERROR Loading translation catalog for:  opencpn-vdr_pi
21:37:32.062 MESSAGE OCPNPlatform.cpp:1101 ERROR Loading translation catalog for:  opencpn-weatherfax_pi
21:37:32.062 MESSAGE OCPNPlatform.cpp:1111 Loading catalog for opencpn core.
21:37:32.062 MESSAGE OCPNPlatform.cpp:952 Getting DefaultSystemLocale...



```

**Comment by rgleason** [comment]
Some more log errors on startup.  Seems to hang up Opencpn.

There are other plugin errors here too.
[Startup-errors-Windows.txt](https://github.com/douwefokkema/AutoTrackRaymarine_pi/files/9022199/Startup-errors-Windows.txt)

**Comment by douwefokkema** [comment]
Rick, did you define a serial port in preferences? If so, is a NGT-1 connected to this port?

**Comment by douwefokkema** [comment]
I am on the boat now and have the NGT1 here. I will do some further testing coming days. Better pause the new release.

**Comment by douwefokkema** [comment]
I tested this morning, sailed and tested the plugin. Working fine. One issue, on my (slow) ships computer I get a crash in O when disabling the plugin (with NGT-1 connected) from the plugin manager. Closing down OpenCPN is fine however. This issue can not be reproduced on my faster dev system.

**Comment by rgleason** [comment]
Douwe, no I didnt define a port!
and I dont have an artisense.
I just tried it.
I think we need to have some prompts just like that when the errors occur for new users,
Along with a prompt that this pi is for raymarine evo!

**Comment by rgleason** [comment]
After these errors occur and the prompts come up, can the pi be unenabled to prevent the crash?

**Comment by rgleason** [comment]
Douwe off sailing, did not rebuild it yet, will do in several days.

**Comment by douwefokkema** [comment]
Good idea, I will do some decent messages for the "just try it". Actually the crash only occurs with a NGT-1 connected and only on slower systems. Working on it in between the sailing.

**Comment by douwefokkema** [comment]
Crash at deactivate is solved. Crash was in O in OcpnLog::DoLogRecord, illegal pointer to the file name. Caused by the plugin doing log output after de-activate. Receive thread took some time stopping. I pushed new version.

**Comment by rgleason** [comment]
Great. Closing. Ok?
